### ISSUE TITLE
can't run plugin.initialize_gettext() ?

### ISSUE THREAD

**Issue by gordielachance** [romanvm/script.module.simpleplugin#1]
Hi romanvm !!!
I'm trying to build my first plugin with simpleplugin, it's my first time with Python too :)

My first tests are fine and i'm already getting some good results with the plugin.
I'm now trying to use localization :

```
# Create plugin instance
plugin = Plugin()

# initialize_gettext
_ = plugin.initialize_gettext()

```

But it crashes Kodi :

> 13:20:09 T:123145306673152   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.TypeError'>
>                                             Error Contents: 'str' object is not callable
>                                             Traceback (most recent call last):
>                                               File "/Users/Gordie/Library/Application Support/Kodi/addons/plugin.audio.subsonic2/main.py", line 23, in <module>
>                                                 _ = plugin.initialize_gettext()
>                                             TypeError: 'str' object is not callable
>                                             -->End of Python script error report<--
> 13:20:09 T:140735162187776   ERROR: GetDirectory - Error getting plugin://plugin.audio.subsonic2/

Could you help me here ?

Thanks !

**Comment by romanvm** [comment]
Some snippets from traceback and code are not informative. Show me your full plugin with all files.

**Comment by gordielachance** [comment]
here you are : http://pastebin.com/4sgwjUgd

**Comment by romanvm** [comment]
Several notes:

1. Please carefully read add the docs, including API docs. `Plugin` class inherits from `Addon` so you don't need to use both. Also `Addon` class has several helper methods and properties to access addon data, so generally you don't need to access the underlying `xbmcaddon.Addon` class. Plugin settings are better accessed via instance properties. Numeric and boolean settings are automatically converted into respective Python types and vice versa.
2. You seem to be using some old version of `simpleplugin` library that does not have `initialize_gettext` method. The current version is **2.0.1** and can be downloaded from "Releases" tab.
3. In v.2+ the recommended way to add actions is via `@plugin.action()` decorator. This makes code more readable and Pythonic. The old method still works but it's less convenient IMO, so I've added the decorator.

The example plugin needs to be updated, but the documentation is current and should be your primary source of information.

**Comment by gordielachance** [comment]
Sorry, you can see the code here : https://github.com/gordielachance/plugin.audio.subsonic

**Comment by romanvm** [comment]
Have you read my reply above? Most probably you are using a very old version of SimplePlugin that does not support the method in question.

**Comment by gordielachance** [comment]
Thanks ! 
Perfect, it works.  I've implemented your remarks.
Yet I don't know why SimplePlugin wasn't up to date in KODI.  Is the last release available from the offical repositories ?

**Comment by romanvm** [comment]
The new procedure for submitting addons into the official Kodi repo is too fussy, so I don't update the plugin. It seems that nobody uses it anyway. You are the first I know besides myself.

**Comment by gordielachance** [comment]
Okay !  But then, it means that it would be smarter that I include directly your library inside the plugin than rely on a dependency that will be out-of-date if a user install the plugin ?

**Comment by gordielachance** [comment]
And do you know why nobody uses your framework ?  It looks great.  I read about [xbmcswift2](https://xbmcswift2.readthedocs.io/en/latest/index.html) but I thought it was not longer maintained..

**Comment by gordielachance** [comment]
> The new procedure for submitting addons into the official Kodi repo is too fussy, so I don't update the plugin. It seems that nobody uses it anyway. You are the first I know besides myself.

But in a way, this is nonsense :)
Would be great to have it in the repo so it can be used as a dependency.

**Comment by romanvm** [comment]
I use this library for my personal projects so a new version is automatically pushed to my private repo: https://github.com/romanvm/kodi_repo

**Comment by gordielachance** [comment]
I understand, it's not a big deal for me to get the latest version.

But the purpose of the addon i'm building is to publish it, so I need to
find a way to ship the lastest version of your library with it...

2016-10-03 16:52 GMT+02:00 Roman Miroshnychenko <notifications@github.com>:
