### ISSUE TITLE
KeyError 'hash' sometimes not found in gettext.pcl

### ISSUE THREAD

**Issue by SylvainCecchetto** [romanvm/script.module.simpleplugin#11]
Hi,

We don't know why, but sometimes the 'hash' key is not find in the gettext.pcl file in this code portion: https://github.com/romanvm/script.module.simpleplugin/blob/ba8bd84693c214f808a4f68a6e3d930c22a3620f/script.module.simpleplugin/libs/simpleplugin.py#L773 

Currently we fix this issue with:
```
if (not os.path.exists(os.path.join(self._configdir, gettext_pcl)) or
    'hash' not in raw_strings_hash or
    raw_strings_hash != ui_strings_map['hash']):
```

Do you know why this issue some time append?

Thank you

**Comment by romanvm** [comment]
I never experienced this issue. Unfortunately, because of the current circumstances I have to suspend the project, meaning that it won't receive any updates or support from now on.

**Comment by SylvainCecchetto** [comment]
Some users of our plugin sometimes experiences this issue. Maybe due to gettext.pcl file corrupted if Kodi or the OS crash during its construction? I don't know ...

Oh really? We really liked to work with it! Hope that someone can take the lead for any support and update for Kodi 18 and more!

Thank you for your work for this lib!

**Comment by colec74** [comment]
I just found this project today... Just my luck it's suspended.

**Comment by vlmaksime** [comment]
@romanvm 
We discussed this problem here: http://xbmc.ru/forum/showthread.php?t=14290&p=119220
Then you suggested a solution: http://xbmc.ru/forum/showthread.php?t=14290&p=119332

**Comment by romanvm** [comment]
@vlmaksime Yes, I totally forgot about that.

If you wish to take over supporting this project, I can add you as a collaborator. Если вы хотите заниматься этим проектом, я могу добавить вас как коллаборатора с полным доступом к коду.

**Comment by vlmaksime** [comment]
@romanvm я боюсь накосячить и все сломать. Может лучше вносить изменения через запросы, чтоб Вы могли контролировать качество кода.

**Comment by romanvm** [comment]
Как я уже написал в Readme, в настоящее время в силу ряда личных причин у меня нет возможности заниматься этим проектом, поэтому его разработка и поддержка приостановлены на неопределенное время.

**Comment by vlmaksime** [comment]
Ну тогда давайте права соавтора, постараюсь не косячить.

**Comment by vlmaksime** [comment]
This issue was fixed in v2.3.3
