### ISSUE TITLE
is it possible to use default 'audio switcher menu' in kodi addons?

### ISSUE THREAD

**Issue by byaka** [romanvm/script.module.simpleplugin#12]
Site that im scrapping allows watching episodes with different audio tracks. Technically its different video files. But how can i give user ability to switch them? Ideally i want to fill and 'hook' default audio-switcher menu. But googling shows me nothing

**Comment by vlmaksime** [comment]
1. Думаю, можно перейти на русский
2. Предлагаю продолжить дискуссию тут: http://xbmc.ru/forum/showthread.php?t=14290
3. Насколько я знаю, KODI нет возможности передать несколько аудиопотоков. Только отдельные ссылки на каждую озвучку. Как вариант, разбивать озвучки по папкам или добавить выбор озвучки в списке эпизодов

**Comment by byaka** [comment]
понятно, спасибо
