### ISSUE TITLE
implement context menu options

### ISSUE THREAD

**Issue by gordielachance** [romanvm/script.module.simpleplugin#2]
Hi again !

Is it how I'm supposed to implement context menu options ?
Can't see them when right-clicking an album item however...

https://github.com/gordielachance/plugin.audio.subsonic/commit/7bfc519b5e2d57ee4b5a099586e275625aba6102

**Comment by romanvm** [comment]
This question is covered in the documentation: http://romanvm.github.io/script.module.simpleplugin/_actions/vf.html

**Comment by gordielachance** [comment]
I found out by digging into xbmcswift2 : 

```
        'context_menu': [
            (
                'Star Album', 
                'XBMC.RunPlugin(%s)' % plugin.get_url(action='star_item',type='album',id=item.get('id'))
            ),
            (
                'Download Album', 
                'XBMC.RunPlugin(%s)' % plugin.get_url(action='download_item',type='album',id=item.get('id'))
            )
        ]
```

**Comment by romanvm** [comment]
Be careful with xbmcswift2. Yes, SimplePlugin was inspired by xbmcswift2 and has some similarities, but they are not the same. If SimplePlugin documentation is not clear enough on some matters, I'm open to suggestions, but it should be your starting point. Also my [ex.ua.alternative](https://github.com/romanvm/ex.ua.alternative) plugin is basically a reference implementation that uses most of SimplePlugin features. Don't mind the readme in Russian, docstrings and comments in the code are in English.
