### ISSUE TITLE
statement for @plugin.cached ?

### ISSUE THREAD

**Issue by gordielachance** [romanvm/script.module.simpleplugin#3]
Hi,  is it possible to have a statement before firing @plugin.cached ?

I mean, something like 

```
@plugin.action()
if cache_minutes:
    @plugin.cached(cache_minutes)
def list_artists(params):
```

currently, it fires a 'invalid syntax' error...

**Comment by romanvm** [comment]
Decorator syntax is a part of the Python specification and you can't change it.

**Comment by romanvm** [comment]
If you want to implement conditional caching you need to wrap your function that needs caching into a proxy function and decorate this proxy. Then call either your function directly or the proxy function depending on a condition.

**Comment by gordielachance** [comment]
Ok.  Another way could be to be able to set the cache timing value to 0, but I saw in your docs that zeo means no limit for it ?

**Comment by romanvm** [comment]
> Ok. Another way could be to be able to set the cache timing value to 0, but I saw in your docs that zeo means no limit for it ?

That behavior was changed in v.2 and now zero duration will raise `ValueError`. Where exactly have you seen this in the docs? If old info is left somewhere, I need to correct it.

Also note that decorators are executed at import time, not at runtime, so you cannot actually pass variable arguments to them. This is not well documented in Python docs, so you need to know it.

**Comment by gordielachance** [comment]
This is what I had read, but I was wrong, you were talking about negative values.

> By providing a negative duration value to the decorator you can store function’s return data forever (or, more exactly, as long as the cache file cache.pcl exists the plugin’s profile folder).

Anyway, a zero duration should just be ignored, no ?

**Comment by romanvm** [comment]
Yes, I forgot to remove that part from the docs. Now only positive values are allowed, otherwise `ValueError` will be raised.
