### ISSUE TITLE
Version constant ?

### ISSUE THREAD

**Issue by gordielachance** [romanvm/script.module.simpleplugin#4]
Hi, in the idea of shipping the simpleplugin.py file with my Kodi Addon,
I was wondering if there was somewhere a way to retrieve the version number of the library.
So I could try to load it, check its version, and warn the user if he has to update it.
Is this available somewhere ?

Thanks !

**Comment by romanvm** [comment]
Version is provided in `addon.xml`. If you are going to include the module in your addon, then why bother with updates? You are targeting a specific feature set anyway.

And a user won't be able to update the library anyway, it's supposed to be an automatic process if you are using the library packed as an addon.

**Comment by gordielachance** [comment]
Yes, I know, there is a problem in the idea.
But if you don't push the addon updates in the official repos, how can a lamba user update it ?
I mean, the 2.0.1 is not in the official repos.  I had to download it manually, and i'm not sure everybody understands how to do that.
That's what I was telling [here](https://github.com/romanvm/script.module.simpleplugin/issues/1#issuecomment-251128842) :)
Sorry again to bother, it's all new stuff for me.
So you think I should not include the addon and let the user find a way to install it ?

**Comment by romanvm** [comment]
Just put `simpleplugin.py` into your addon. It's a single file no third-party dependencies, and it's GPL licensed. And if everything works fine in your addon, then why bother with updates? "Don't fix it if it ain't broken". I sometimes include third-party libraries in my addons and if everything works fine just leave them alone.

**Comment by gordielachance** [comment]
Yeah, I guess you are right !

**Comment by gordielachance** [comment]
...But it would be great too to have a constant in your py file.
If I include simpleplugin.py in my addon; then that you update that file, I have no clue to find out what version it is, you see ?
Thanks.

**Comment by romanvm** [comment]
Then I will have to maintain a version number in 2 places: in `addon.xml` and in the code, which is error-prone because I may accidentally forget to keep the versions in sync. So that's a "no". If you need a version number, put it yourself in your copy. The GPL license allows you to modify the code without limitations, provided you publish a modified version or readily provide it by request.
