### ISSUE TITLE
Error if only one sort_method provided

### ISSUE THREAD

**Issue by SylvainCecchetto** [romanvm/script.module.simpleplugin#5]
Hi,

Thanks a lot for your framework.

I think there is a bug concerning sort_methods, if you provide only one sort_method during the listing creation I have this error :

```
[xbmcplugin.addSortMethod(self._handle, method) for method in context.sort_methods]
TypeError: 'int' object is not iterable
```

I have to put at least two sorts methods.

This code works :

```
sort_methods = (
        xbmcplugin.SORT_METHOD_UNSORTED,
        xbmcplugin.SORT_METHOD_UNSORTED
)
return common.plugin.create_listing(
    listing,
    sort_methods=sort_methods
)
```

But not this one : 

```
sort_methods = (
        xbmcplugin.SORT_METHOD_UNSORTED
)
return common.plugin.create_listing(
    listing,
    sort_methods=sort_methods
)
```

Thanks !

**Comment by romanvm** [comment]
You have a syntax error in your `sort_methods` rvalue. Please read Python manuals about `tuple` literals syntax: https://www.tutorialspoint.com/python/python_tuples.htm
