### ISSUE TITLE
New path for strings.po file

### ISSUE THREAD

**Issue by SylvainCecchetto** [romanvm/script.module.simpleplugin#6]
Hi romanvm,

I use your framework for my personnel plugin and I like it so much!

During my last update on the official Kodi repo one of the reviewer ask me to change the path of my strings.po file like this:
`resources/language/resource.language.en_gb/strings.po`

I don't know why, maybe it's a new "rule".

So I had to change the line 746 in the simpleplugin.py according to the new path:

* Before:
`strings_po = os.path.join(self.path, 'resources', 'language', 'English', 'strings.po')`
* Now:
`strings_po = os.path.join(self.path, 'resources', 'language', 'resource.language.en_gb', 'strings.po')`

I don't know if you have to change this line in your repo but it's only to inform you about that!

Just in case this the concerned PR: https://github.com/xbmc/repo-plugins/pull/1197

Sylvain

**Comment by romanvm** [comment]
Thanks for noticing. I know about the addon layout change but haven't fixed it yet.
